# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: FIRST Lego League Camp
description: > # this means to ignore newlines until "baseurl:"
  FIRST Lego League Camp is a week long day camp for kids in elementary and middle school
  interested in and engaged with engineering and problem-solving. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://lauraschultz.github.io/fllcamp" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
